spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_practice?serverTimezone=UTC&useSSL=false
    username: root
    password: 1q2w3e4r!!A
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug